services:
  mlserver:
    container_name: mlserver-model
    image: acrola/proyek_sml_kenny:latest # Docker image
    ports:
      - "8001:8080" # For accessing the inference endpoint (from exporter)
      - "8082:8082" # MLServer's built-in metrics endpoint
    environment:
      MLSERVER_METRICS_PORT: 8082 # Port for MLServer metrics
      MLSERVER_METRICS_ENDPOINT: /metrics
    networks:
      - model-monitoring-net

  custom-metrics-exporter: # NEW SERVICE for custom exporter
    container_name: custom-metrics-exporter
    build:
      context: . # Assumes Dockerfile.exporter and prometheus_exporter.py are in this directory
      dockerfile: Dockerfile.exporter
    ports:
      - "5000:5000" # Expose the exporter's Flask app port (and its /metrics endpoint)
    networks:
      - model-monitoring-net
    depends_on:
      - mlserver # This exporter needs MLServer to be running to proxy requests

  prometheus:
    container_name: prometheus-server
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Mount the Prometheus config file
    ports:
      - "9090:9090" # Prometheus UI
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - mlserver
      - custom-metrics-exporter # Prometheus depends on both MLServer and the Exporter
    networks:
      - model-monitoring-net

  grafana:
    container_name: grafana-dashboards
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - model-monitoring-net
    environment:
      # SMTP Server Configuration
      GF_SMTP_ENABLED: true
      GF_SMTP_HOST: smtp.gmail.com:587 
      GF_SMTP_USER: <your email>@gmail.com # Your Gmail address
      GF_SMTP_PASSWORD: <your app password> # Use an App Password for Gmail
      GF_SMTP_FROM_ADDRESS: your_email@gmail.com # The "From" email in the alert
      GF_SMTP_FROM_NAME: GrafanaAlerts # The "From" name in the alert
      GF_SMTP_SKIP_VERIFY: false 
      GF_SMTP_STARTTLS_AUTO: true # Use STARTTLS for port 587
      GF_SMTP_EHLO_HOSTNAME: grafana.example.com

      # General Alerting Settings
      GF_ALERTING_ENABLED: true
      GF_ALERTING_MIN_INTERVAL_SECONDS: 10 # Minimum time between alert evaluations

volumes:
  grafana-storage: {}

networks:
  model-monitoring-net: {}